name: docker release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'     
      - name: Log in to the ghcr.io
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}    
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1.5.0
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      # - name: Build Custom War Package
      #   run: ./setup.sh
      #   shell: bash
      # - name: Build base image
      #   uses: docker/build-push-action@v2.6.1
      #   with:
      #     file: out/tmp/output/Dockerfile
      #     context: out/tmp/output/
      #     load: true
      #     tags: jenkins-local/jenkinsfile-runner-single:latest
      # - name: Build Docker image
      #   uses: docker/build-push-action@v2.6.1
      #   with:
      #     file: Dockerfile
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      - name: test1
        uses: docker/build-push-action@v2.6.1
        with:
          file: Dockerfile1
          load: true
          tags: jenkins-local/jenkinsfile-runner-single:latest
      - run: docker images
        shell: bash
      - name: test2
        uses: docker/build-push-action@v2.6.1
        with:
          file: Dockerfile2
          load: true
          tags: jenkins-remote/jenkinsfile-runner-single:latest           