name: docker release
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  dry_run_action:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al ${{ github.workspace }}
        shell: bash
      # - uses: addnab/docker-run-action@v3
      #   with: 
      #     image: jenkins/jenkinsfile-runner:latest
      #     shell: bash
      #     options: -v ${{ github.workspace }}:/work -w /work -e ACTIONS_CACHE_URL -e GITHUB_REF
      #     run: ls -al /work && /work/entrypoint.sh
  build-and-publish:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'     
      - name: Log in to the ghcr.io
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}    
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build Docker image
        uses: docker/build-push-action@v2.6.1
        with:
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}        